# SPDX-License-Identifier: GPL-2.0
# A546B
dtbo-y += \
        a54x_eur_open_w00_r00.dtbo \
        a54x_eur_open_w00_r01.dtbo \
        a54x_eur_open_w00_r02.dtbo \
        a54x_eur_open_w00_r03.dtbo \
        a54x_eur_open_w00_r05.dtbo \
        a54x_eur_open_w00_r10.dtbo

# A546E
dtbo-y += \
        a54x_sea_open_w00_r00.dtbo \
        a54x_sea_open_w00_r02.dtbo \
        a54x_sea_open_w00_r03.dtbo \
        a54x_sea_open_w00_r05.dtbo

# A546J - Japan
dtbo-y += \
	a54x_jpn_kdi_w00_r00.dtbo \
	a54x_jpn_kdi_w00_r04.dtbo \
	a54x_jpn_kdi_w00_r05.dtbo

always-y    := $(dtb-y) $(dtbo-y)
subdir-y    := $(dts-dirs)
clean-files    := *.dtb *.reverse.dts *.dtbo
