name: Build release

on:
  workflow_dispatch:

jobs:
  build_kernel:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target: [clean, permissive, ksu, ksu-sus, ksu-next, sukisu]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up build environment
        run: |
          sudo apt update && sudo apt upgrade
          sudo apt-get remove --purge -y "php*" "dotnet*" "mysql*" "clang*" "google*"
          sudo apt autoremove -y
          sudo apt install -yq tar \
            attr libelf-dev dwarves rsync libbrotli-dev \
            libgtest-dev libprotobuf-dev libunwind-dev libusb-1.0-0-dev libzstd-dev libc6-dev \
            linux-modules-extra-$(uname -r) build-essential p7zip-full libarchive-tools
          
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Fetch ToolChain
        run: |
          mkdir -p ~/Prebuilts
          mkdir -p ~/Prebuilts/clang-r450784c
          wget -c https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/llvm-r450784/clang-r450784c.tar.gz -O clang.tar.gz
          tar -xf clang.tar.gz -C ~/Prebuilts/clang-r450784c

      - name: Fetch AnyKernel
        run: |
          git clone --branch a54x https://github.com/Vaz15k/AnyKernel3.git ~/AnyKernel
          mkdir -p ~/files

      - name: Set date variable
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV      

      - name: Build Kernel Clean
        if: matrix.target == 'clean'
        run: |
          ./build/build.sh
          cp ~/AnyKernel/Squeak* ~/files

      - name: Build Kernel With KSU
        if: matrix.target == 'ksu'
        run: |
          ./build/build.sh --ksu
          cp ~/AnyKernel/Squeak* ~/files

      - name: Build Kernel With KSU-SUS
        if: matrix.target == 'ksu-sus'
        run: |
          ./build/build.sh --ksu --susfs
          cp ~/AnyKernel/Squeak* ~/files

      - name: Build Kernel With KSU-NEXT
        if: matrix.target == 'ksu-next'
        run: |
          ./build/build.sh --next --susfs
          cp ~/AnyKernel/Squeak* ~/files

      - name: Build Kernel with SukiSU
        if: matrix.target == 'sukisu'
        run: |
          ./build/build.sh --sukisu
          cp ~/AnyKernel/Squeak* ~/files

      - name: Build Permissive Kernel
        if: matrix.target == 'permissive'
        run: |
          ./build/build.sh --permissive
          cp ~/AnyKernel/Squeak* ~/files

      - name: Publish to GitHub
        id: release
        uses: softprops/action-gh-release@v2
        with:
          files: /home/runner/files/*
          name: Squeak Kernel - ${{ env.DATE }}
          tag_name: "${{ env.DATE }}"
          body: |
            ## Managers
            - **KernelSU:** https://github.com/tiann/KernelSU/releases
            - **KernelSU-SusFS:** https://github.com/rsuntk/KernelSU/releases
            - **KernelSU-NEXT:** https://github.com/KernelSU-Next/KernelSU-Next/releases
            - **SukiSU:** https://github.com/SukiSU-Ultra/SukiSU-Ultra/releases
            ---
            - **Kernel Version:** 5.15.153
            - **Clang Version:** Clang-r450784c
            :rocket: *Built with love by GitHub Actions.*
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
